version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/openjdk:11-jdk-stretch # OpenJDK on Debian 9 Stretch Docker container
    steps:
      - git clone https://github.com/kruegersp/cc.git # check out the CARMAcloud code
