version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/openjdk:11-jdk-stretch # OpenJDK on Debian 9 Stretch Docker container
    working_directory: /tmp
    steps:
      - run: git clone https://github.com/kruegersp/cc.git
      - run: java -version
