version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch # OpenJDK on Debian 9 Stretch Docker container
    working_directory: /tmp
    steps:
      - run:
          command: |
            git clone https://github.com/kruegersp/cc.git
            rm cc/src/cc/util/TileUtil.java
            rm -r cc/src/cc/vector_tile
            rm cc/src/cc/ws/XodrTiles.java
            mkdir -p cc/build
            find -name "*.java" > sources.txt
            javac -cp cc/lib/commons-compress-1.18.jar:cc/lib/geronimo-servlet_3.0_spec-1.0.jar:cc/lib/javax.json.jar -d cc/build -Xlint:deprecation @sources.txt
            find -name "*.class"
