version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch # OpenJDK on Debian 9 Stretch Docker container
    working_directory: /tmp
    steps:
      - run:
          command: |
            git clone https://github.com/kruegersp/cc.git
            rm cc/util/TileUtil.java
            rm -r cc/vector_tile
            rm cc/ws/XodrTiles.java
            mkdir build
            find -name "*.java" > sources.txt
            cat sources.txt
            javac -d build @sources.txt
