version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch # OpenJDK on Debian 9 Stretch Docker container
    working_directory: /tmp
    steps:
      - run: wget http://apache.mirrors.lucidnetworks.net/tomcat/tomcat-9/v9.0.24/bin/apache-tomcat-9.0.24.tar.gz
      - run: tar -xf apache-tomcat-9.0.24.tar.gz -C tomcat
      - run: git clone https://github.com/kruegersp/cc.git
      - run: find ./cc/src -name "*.java" > sources.txt
      - run: mkdir -p tomcat/webapps/carmacloud/ROOT/WEB-INF/classes
      - run: javac -cp tomcat/lib/servlet-api.jar:cc/lib/commons-compress-1.18.jar:cc/lib/javax.json.jar:cc/lib/protobuf-javalite-3.8.0-rc-1.jar -d tomcat/webapps/carmacloud/ROOT/WEB-INF/classes @sources.txt
