version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/openjdk:11-jdk-stretch # OpenJDK on Debian 9 Stretch Docker container
    working_directory: /tmp
    steps:
      - run:
         name: Deploy if tests pass and branch is Staging
         command: git clone https://github.com/kruegersp/cc.git # check out the CARMAcloud code
